# Generated by Django 4.2.7 on 2026-05-17 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('total_points', models.IntegerField(default=0)),
                ('tier', models.TextField(default='Bronze')),
                ('points_to_next_tier', models.IntegerField(default=0)),
                ('lifetime_points_earned', models.IntegerField(default=0)),
                ('lifetime_points_redeemed', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('type', models.TextField()),
                ('points', models.IntegerField()),
                ('reason', models.TextField()),
                ('rental_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
