# Generated by Django 4.2.7 on 2026-05-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_reward_rewardtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardtransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
