# Generated by Django 4.2.7 on 2026-05-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_rewardtransaction_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='timestamp',
            new_name='updated_at',
        ),
    ]
